### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by sultanqasim**
- More FFT timespan and waterfall update rate options
- Finer frequency resolution (larger FFT size) for panoramic spectrum to see narrower frequency peaks in wide frequency ranges
- Quicker GUI timer interval so that playback progress bar updates more smoothly (visually appealingly) on short recordings
- Properly handle setting the sample rate and center frequency when loading recordings for playback
- Fix some compiler warnings

### CODE REVIEW

**Comment by BatchDrake** [comment]
Looks good too, will test it along with your PR for suscan. Thanks!

**Comment by BatchDrake** [comment]
There's a little UI issue with these changes in the Source config tab (ProfileConfigTab). If you attempt to navigate through all source types with the mouse wheel or the arrow keys, sometimes the current source type is not reflected in the source type combo / source config UI stack (although it does in the ProfileConfigTab state and the underlying Suscan::Source::Config object).

**Comment by sultanqasim** [comment]
Thanks for your testing, I’ll look into that bug

**Comment by melroy89** [comment]
@BatchDrake you need some help with those failing tests?

**Comment by BatchDrake** [comment]
Hi,

I plan to get back to this soon, but I am afraid I will not find time until the week of December 18th or so.

Cheers,

**Comment by sultanqasim** [comment]
I need to recreate the bug BatchDrake encountered regarding ProfileConfigTab and then find the root cause. Maybe I’ll have time this week.

**Comment by BatchDrake** [comment]
Fixed. It had to do with signals being emitted at the wrong time (source config widget activation). I've just prevented this explicitly.

**Comment by sultanqasim** [comment]
Thanks for figuring this out! Sorry, I haven’t gotten to spend much time on SigDigger lately though I’m still hoping to get back to it soon.

**Comment by BatchDrake** [comment]
No worries, I was waiting for a 3D print to finish and decided to close as
many PRs as possible today :)

**Pull request merged**
